image:
  repository: 304896961232.dkr.ecr.eu-central-1.amazonaws.com/petclinic-dev-config-server
  tag: "latest"
containerPort: 8888
service:
  type: ClusterIP
  port: 8888
namespace: petclinic-dev
waitForConfigServer: false
extraEnv:
  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
    value: "https://github.com/spring-petclinic/spring-petclinic-microservices-config"
  - name: SPRING_PROFILES_ACTIVE
    value: "docker,native"
